# Generated by Django 3.0.3 on 2020-06-06 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 19, 43, 29, 627275)),
        ),
    ]
